package com.tekfilo.jewellery.util;

public enum UploadTypes {
    FG_PURCHASE,
    FG_SALES,
    FG_MEMO_PURCHASE,
    FG_MEMO_SALES,
    FG_PURCHASE_RETURN,
    FG_SALES_RETURN,
    FG_MEMO_PURCHASE_RETURN,
    FG_MEMO_SALES_RETURN,
    JEW_PURCHASE,
    JEW_SALES,
    JEW_MEMO_PURCHASE,
    JEW_MEMO_SALES,
    JEW_PURCHASE_RETURN,
    JEW_SALES_RETURN,
    JEW_MEMO_PURCHASE_RETURN,
    JEW_MEMO_SALES_RETURN,
    JEWELLERY,
    DESIGN,
    SKU,
    DESIGN_IMAGE,
    SKU_IMAGE,
    JEWELLERY_IMAGE,
    JEW_INWARD,
    JEW_OUTWARD
}
