update tbl_jv_main set inv_type = 'JV' where inv_type is null;
update tbl_jv_main set inv_no = '999999' where inv_no is null;
update tbl_jv_main set inv_dt = current_date where inv_dt is null;
update tbl_jv_main set inv_due_dt = current_date where inv_due_dt is null;
update tbl_jv_main set currency = 'USD' where currency is null;
update tbl_jv_main set exchange_rate = 1 where exchange_rate is null;
ALTER TABLE tbl_jv_main ALTER COLUMN inv_type SET NOT NULL;
ALTER TABLE tbl_jv_main ALTER COLUMN inv_no SET NOT NULL;
ALTER TABLE tbl_jv_main ALTER COLUMN inv_dt SET NOT NULL;
ALTER TABLE tbl_jv_main ALTER COLUMN inv_due_dt SET NOT NULL;
ALTER TABLE tbl_jv_main ALTER COLUMN currency SET NOT NULL;
ALTER TABLE tbl_jv_main ALTER COLUMN exchange_rate SET NOT NULL;
alter table tbl_jv_main add column total_debit_amount   numeric(20,4) default 0 not null;
alter table tbl_jv_main add column total_credit_amount   numeric(20,4) default 0 not null;
alter table tbl_jv_main add column payment_status varchar(30) default 'NEW' not null;
ALTER TABLE tbl_jv_main RENAME COLUMN status TO accounting_status;
ALTER TABLE tbl_jv_main ALTER COLUMN accounting_status SET  default 'UNPOSTED';
-- bank payment and receipt changes
update tbl_bank_pay_rec_main set inv_type = 'BP' where inv_type is null;
update tbl_bank_pay_rec_main set inv_no = '999999' where inv_no is null;
update tbl_bank_pay_rec_main set inv_dt = current_date where inv_dt is null;
update tbl_bank_pay_rec_main set inv_due_dt = current_date where inv_due_dt is null;
update tbl_bank_pay_rec_main set currency = 'USD' where currency is null;
update tbl_bank_pay_rec_main set exchange_rate = 1 where exchange_rate is null;
alter table tbl_bank_pay_rec_main add column  total_debit_amount   numeric(20,4) default 0 not null;
alter table tbl_bank_pay_rec_main add column  total_credit_amount   numeric(20,4) default 0 not null;
alter table tbl_bank_pay_rec_main add column payment_status varchar(30) default 'NEW' not null;
ALTER TABLE tbl_bank_pay_rec_main RENAME COLUMN status TO accounting_status;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN accounting_status SET  default 'UNPOSTED';
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN inv_type SET NOT NULL;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN inv_no SET NOT NULL;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN inv_dt SET NOT NULL;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN inv_due_dt SET NOT NULL;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN currency SET NOT NULL;
ALTER TABLE tbl_bank_pay_rec_main ALTER COLUMN exchange_rate SET NOT NULL;
update tbl_cash_pay_rec_main set inv_type = 'CP' where inv_type is null;
update tbl_cash_pay_rec_main set inv_no = '999999' where inv_no is null;
update tbl_cash_pay_rec_main set inv_dt = current_date where inv_dt is null;
update tbl_cash_pay_rec_main set inv_due_dt = current_date where inv_due_dt is null;
update tbl_cash_pay_rec_main set currency = 'USD' where currency is null;
update tbl_cash_pay_rec_main set exchange_rate = 1 where exchange_rate is null;
alter table tbl_cash_pay_rec_main add column total_debit_amount   numeric(20,4) default 0 not null;
alter table tbl_cash_pay_rec_main add column total_credit_amount   numeric(20,4) default 0 not null;
alter table tbl_cash_pay_rec_main add column payment_status varchar(30) default 'NEW' not null;
ALTER TABLE tbl_cash_pay_rec_main RENAME COLUMN status TO accounting_status;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN accounting_status SET  default 'UNPOSTED';
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN inv_type SET NOT NULL;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN inv_no SET NOT NULL;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN inv_dt SET NOT NULL;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN inv_due_dt SET NOT NULL;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN currency SET NOT NULL;
ALTER TABLE tbl_cash_pay_rec_main ALTER COLUMN exchange_rate SET NOT NULL;


update tbl_debit_credit_note_main set inv_type = 'NDR' where inv_type is null;
update tbl_debit_credit_note_main set inv_no = '999999' where inv_no is null;
update tbl_debit_credit_note_main set inv_dt = current_date where inv_dt is null;
update tbl_debit_credit_note_main set inv_due_dt = current_date where inv_due_dt is null;
update tbl_debit_credit_note_main set currency = 'USD' where currency is null;
update tbl_debit_credit_note_main set exchange_rate = 1 where exchange_rate is null;

update tbl_debit_credit_note_main set inv_due_months = 0 where inv_due_months is null;
update tbl_debit_credit_note_main set inv_due_days = 0 where inv_due_days is null;
update tbl_debit_credit_note_main set party_type = 'SUPPLIER' where party_type is null;
update tbl_debit_credit_note_main set party_id = -1 where party_id is null;
update tbl_debit_credit_note_main set payment_type_id = -1 where payment_type_id is null;
update tbl_debit_credit_note_main set payment_status = 'NEW' where payment_status is null;
update tbl_debit_credit_note_main set accounting_status = 'UNPOSTED' where accounting_status is null;
alter table tbl_debit_credit_note_main add column total_debit_amount   numeric(20,4) default 0 not null;
alter table tbl_debit_credit_note_main add column total_credit_amount   numeric(20,4) default 0 not null;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_type SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_no SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_dt SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_due_dt SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN currency SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN exchange_rate SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_due_months SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_due_days SET NOT NULL;

ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_due_months SET default 0;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN inv_due_days SET  default 0;

ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN party_type SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN party_id SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN payment_type_id SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN payment_status SET NOT NULL;
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN accounting_status SET NOT NULL ;

ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN payment_status SET  default 'NEW';
ALTER TABLE tbl_debit_credit_note_main ALTER COLUMN accounting_status SET  default 'UNPOSTED';
