alter table tbl_jew_purchase_invoice_main add column order_id integer;
alter table tbl_jew_purchase_return_invoice_main add column order_id integer;
alter table tbl_jew_memo_purchase_invoice_main add column order_id integer;
alter table tbl_jew_memo_purchase_return_invoice_main add column order_id integer;
alter table tbl_jew_sales_invoice_main add column order_id integer;
alter table tbl_jew_sales_return_invoice_main add column order_id integer;
alter table tbl_jew_memo_sales_invoice_main add column order_id integer;
alter table tbl_jew_memo_sales_return_invoice_main add column order_id integer;
alter table tbl_jew_purchase_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_return_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_return_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_return_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_purchase_return_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_return_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_return_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_return_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_purchase_return_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_sales_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_sales_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_sales_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_sales_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_sales_return_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_sales_return_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_sales_return_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_sales_return_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_return_invoice_main add column party_payable_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_return_invoice_main add column charges_plus_amount    numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_return_invoice_main add column charges_minus_amount   numeric(20,4) default 0 not null;
alter table tbl_jew_memo_sales_return_invoice_main add column total_invoice_gross_amount numeric(20,4) default 0 not null;
alter table tbl_jew_sales_return_invoice_main add column note 	text;
alter table tbl_jew_sales_return_invoice_main add column terms_conditions text;
alter table tbl_jew_memo_purchase_invoice_det add column ref_inv_type varchar(30);
alter table tbl_jew_memo_purchase_invoice_det add column ref_inv_id integer;
alter table tbl_jew_memo_purchase_invoice_det add column ref_inv_det_id integer;
ALTER TABLE tbl_jewellery ADD CONSTRAINT jew_no_uk UNIQUE (jew_type,jew_no);
ALTER TABLE tbl_jewellery_stock_trans ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock_trans ALTER COLUMN jew_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock_trans ALTER COLUMN bin_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock_trans ALTER COLUMN inv_dt SET NOT NULL;
ALTER TABLE tbl_jewellery_stock_trans ALTER COLUMN in_out_flag SET NOT NULL;
ALTER TABLE tbl_jewellery_stock_trans add COLUMN exchange_rate  numeric(20,4) default 0 not null;
ALTER TABLE tbl_jewellery_stock_trans ADD CONSTRAINT trans_company_fk1 FOREIGN KEY (company_id) REFERENCES public.tbl_company(company_id);
ALTER TABLE tbl_jewellery_stock_trans ADD CONSTRAINT trans_jew_fk1 FOREIGN KEY (jew_id) REFERENCES tbl_jewellery(jew_id);
ALTER TABLE tbl_jewellery_stock_trans ADD CONSTRAINT trans_bin_fk1 FOREIGN KEY (bin_id) REFERENCES tbl_bin(bin_id);
---Product Stock changes
ALTER TABLE tbl_jewellery_stock ALTER COLUMN company_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock ALTER COLUMN jew_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock ALTER COLUMN bin_id SET NOT NULL;
ALTER TABLE tbl_jewellery_stock ADD CONSTRAINT stock_company_fk1 FOREIGN KEY (company_id) REFERENCES public.tbl_company(company_id);
ALTER TABLE tbl_jewellery_stock ADD CONSTRAINT stock_jew_fk1 FOREIGN KEY (jew_id) REFERENCES tbl_jewellery(jew_id);
ALTER TABLE tbl_jewellery_stock ADD CONSTRAINT stock_bin_fk1 FOREIGN KEY (bin_id) REFERENCES tbl_bin(bin_id);

alter table tbl_jewellery add document_url text;
ALTER TABLE tbl_jew_bin_transfer_det DROP CONSTRAINT positive_qty;
ALTER TABLE tbl_jewellery_stock_trans ADD COLUMN inv_no varchar(30);