
drop table if exists tbl_item_category;
DROP TABLE IF EXISTS tbl_item;

drop table IF EXISTS tbl_item_purchase_invoice_main;
drop table IF EXISTS tbl_item_purchase_invoice_det;
drop table IF EXISTS tbl_item_purchase_invoice_chgs;

drop table IF EXISTS tbl_item_purchase_return_invoice_main;
drop table IF EXISTS tbl_item_purchase_return_invoice_det;
drop table IF EXISTS tbl_item_purchase_return_invoice_chgs;

drop table IF EXISTS tbl_item_sales_invoice_main;
drop table IF EXISTS tbl_item_sales_invoice_det;
drop table IF EXISTS tbl_item_sales_invoice_chgs;

drop table IF EXISTS tbl_item_sales_return_invoice_main;
drop table IF EXISTS tbl_item_sales_return_invoice_det;
drop table IF EXISTS tbl_item_sales_return_invoice_chgs;

drop sequence IF EXISTS tbl_item_category_seq ;
drop sequence IF EXISTS tbl_item_seq;

drop sequence IF EXISTS tbl_item_purchase_invoice_main_seq;
drop sequence IF EXISTS tbl_item_purchase_invoice_det_seq;
drop sequence IF EXISTS tbl_item_purchase_invoice_chgs_seq;

drop sequence IF EXISTS tbl_item_purchase_return_invoice_main_seq;
drop sequence IF EXISTS tbl_item_purchase_return_invoice_det_seq;
drop sequence IF EXISTS tbl_item_purchase_return_invoice_chgs_seq;


drop sequence IF EXISTS tbl_item_sales_invoice_main_seq;
drop sequence IF EXISTS tbl_item_sales_invoice_det_seq;
drop sequence IF EXISTS tbl_item_sales_invoice_chgs_seq;

drop sequence IF EXISTS tbl_item_sales_return_invoice_main_seq;
drop sequence IF EXISTS tbl_item_sales_return_invoice_det_seq;
drop sequence IF EXISTS tbl_item_sales_return_invoice_chgs_seq;


create sequence if not exists tbl_item_category_seq;
create table tbl_item_category
(
    category_id integer not null default nextval('tbl_item_category_seq'),
    category_type   varchar(50),
    category_name   varchar(50),
    description     text,
    is_return   integer default 0 not null,
    unit            varchar(50),
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(category_id)
);

create sequence if not exists tbl_item_seq;
create table if not exists tbl_item
(
    item_id integer not null default nextval('tbl_item_seq'),
    category_id    integer,
    item_type       varchar(50),
    item_name       varchar(50),
    sku_no          varchar(50),
    description text,
    unit varchar(50),
    is_return integer default 0 not null,
    dimension varchar(50),
    dimension_uom varchar(50),
    weight  numeric(20,4) default 0 not null,
    weight_uom varchar(50),
    manufacturer_id integer,
    brand       varchar(50),
    barcode_no varchar(200),
    qrcode_no varchar(200),
    image_url text,
    qty numeric(20,4) default 0 not null,
    currency    varchar(30),
    exchange_rate   numeric(20,4) default 0 not null,
    sales_price numeric(20,4) default 0 not null,
    sales_account_id integer,
    sales_description text,
    cost_price      numeric(20,4) default 0 not null,
    purchase_account_id integer,
    purchase_description text,
    inventory_account_id integer,
    reorder_qty     numeric(20,4) default 0 not null,
    supplier_id     integer,
    company_id      integer not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(item_id)
);

-- Item Invoice modules
create SEQUENCE tbl_item_purchase_invoice_main_seq;
create table if not exists tbl_item_purchase_invoice_main
(
	inv_id 		integer not null default nextval('tbl_item_purchase_invoice_main_seq'),
	inv_type 	varchar(50) not null,
	inv_no 		varchar(50) not null,
	REFERENCE_no 	varchar(50) ,
	inv_dt 			date not null,
	inv_due_dt		date not null,
	inv_due_months 	numeric(20,4) not null,
	inv_due_days 	numeric(20,4) not null,
	currency 		varchar(50) not null,
	exchange_rate 	numeric(20,4) not null,
	supplier_id 	integer not null,
	head_buyer_id 	integer,
	buyer_id 		integer,
	payment_type_id 	integer not null,
	shipment_type_id 	integer,
	shipment_company_name varchar(50),
	carrier_id 			integer,
	tracking_no 		varchar(50),
	tracking_status 	varchar(50),
	inv_status			varchar(50) not null,
	payment_status		varchar(50) not null,
	cancel_hold_status	varchar(50),
	accounting_status	varchar(50) not null,
	document_url		varchar(200),
	order_id            integer,
	total_invoice_qty numeric(20,4) default 0 not null,
	total_invoice_amount	numeric(20,4) default 0 not null,
    party_payable_amount   numeric(20,4) default 0 not null,
    charges_plus_amount    numeric(20,4) default 0 not null,
    charges_minus_amount   numeric(20,4) default 0 not null,
    total_invoice_gross_amount numeric(20,4) default 0 not null,
	total_paid_amount		numeric(20,4) default 0 not null,
	billing_id 		integer,
	bill_address1	varchar(200),
	bill_address2	varchar(200),
	bill_country	varchar(100),
	bill_state		varchar(100),
	bill_city		varchar(100),
	bill_street		varchar(100),
	bill_pincode	varchar(50),
	bill_website	varchar(50),
	bill_phone_no	varchar(50),
	bill_fax_no		varchar(50),
	bill_mobile_no	varchar(50),
	shipping_id 	integer,
	ship_address1	varchar(200),
	ship_address2	varchar(200),
	ship_country	varchar(100),
	ship_state		varchar(100),
	ship_city		varchar(100),
	ship_street		varchar(100),
	ship_pincode	varchar(50),
	ship_website	varchar(50),
	ship_phone_no	varchar(50),
	ship_fax_no		varchar(50),
	ship_mobile_no	varchar(50),
	note 			text,
	terms_conditions text,
	company_id 		integer not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_id),
	CONSTRAINT tbl_item_purchase_invoice_main_fk1 FOREIGN KEY(supplier_id) REFERENCES tbl_supplier(supplier_id),
	constraint tbl_item_purchase_invoice_main_fk2 FOREIGN key(company_id) references public.tbl_company(company_id),
	constraint tbl_item_purchase_invoice_main_fk3 FOREIGN key(payment_type_id) references tbl_payment_type(payment_type_id)
);
create SEQUENCE tbl_item_purchase_invoice_det_seq;
create table if not exists tbl_item_purchase_invoice_det
(
	inv_det_id integer not null default nextval('tbl_item_purchase_invoice_det_seq'),
	inv_id 		integer not null,
	ref_inv_type 	varchar(30),
	ref_inv_id  	integer,
	ref_inv_det_id  integer,
	item_id 	integer not null,
	item_description text,
	bin_id 		integer not null,
	inv_qty	numeric(20,4) default 0 not null,
	uom		varchar(50) not null,
	input_rate	numeric(20,4) default 0 not null,
	input_amt	numeric(20,4) default 0 not null,
	conf_qty	numeric(20,4) default 0 not null,
	ret_qty	numeric(20,4) default 0 not null,
	conf_input_rate	numeric(20,4) default 0 not null,
	conf_input_amt	numeric(20,4) default 0 not null,
	ret_input_rate	numeric(20,4) default 0 not null,
	ret_input_amt	numeric(20,4) default 0 not null,
	discount_type   varchar(50),
	discount_value    numeric(20,4),
	cost_price numeric(20,4) default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_det_id)	,
	CONSTRAINT tbl_item_purchase_invoice_det_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_purchase_invoice_main(inv_id),
	CONSTRAINT tbl_item_purchase_invoice_det_fk2 FOREIGN KEY(item_id) REFERENCES tbl_item(item_id),
	CONSTRAINT tbl_item_purchase_invoice_det_fk3 FOREIGN KEY(bin_id) REFERENCES tbl_bin(bin_id)
);

create SEQUENCE tbl_item_purchase_invoice_chgs_seq;
create table if not exists tbl_item_purchase_invoice_chgs
(
	charge_id  integer not null default nextval('tbl_item_purchase_invoice_chgs_seq'),
	inv_id     			integer not null,
	charge_name      	varchar(100) not null,
	plus_minus_flag  	integer not null,
	input_pct_amt_type 	varchar(50) not null,
	input_pct_amt_value numeric(20,4) default 0 not null,
	input_amt 			numeric(20,4) default 0 not null,
	is_supplier_payable integer default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(charge_id),
	CONSTRAINT tbl_item_purchase_invoice_chgs_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_purchase_invoice_main(inv_id)
);


-- Purchase Return
create SEQUENCE tbl_item_purchase_return_invoice_main_seq;
create table if not exists tbl_item_purchase_return_invoice_main
(
	inv_id 		integer not null default nextval('tbl_item_purchase_return_invoice_main_seq'),
	inv_type 	varchar(50) not null,
	inv_no 		varchar(50) not null,
	REFERENCE_no 	varchar(50) ,
	inv_dt 			date not null,
	inv_due_dt		date not null,
	inv_due_months 	numeric(20,4) not null,
	inv_due_days 	numeric(20,4) not null,
	currency 		varchar(50) not null,
	exchange_rate 	numeric(20,4) not null,
	supplier_id 	integer not null,
	head_buyer_id 	integer,
	buyer_id 		integer,
	payment_type_id 	integer not null,
	shipment_type_id 	integer,
	shipment_company_name varchar(50),
	carrier_id 			integer,
	tracking_no 		varchar(50),
	tracking_status 	varchar(50),
	inv_status			varchar(50) not null,
	payment_status		varchar(50) not null,
	cancel_hold_status	varchar(50),
	accounting_status	varchar(50) not null,
	document_url		varchar(200),
	total_invoice_qty numeric(20,4) default 0 not null,
	total_invoice_amount	numeric(20,4) default 0 not null,
    party_payable_amount   numeric(20,4) default 0 not null,
    charges_plus_amount    numeric(20,4) default 0 not null,
    charges_minus_amount   numeric(20,4) default 0 not null,
    total_invoice_gross_amount numeric(20,4) default 0 not null,
	total_paid_amount		numeric(20,4) default 0 not null,
	billing_id 		integer,
	bill_address1	varchar(200),
	bill_address2	varchar(200),
	bill_country	varchar(100),
	bill_state		varchar(100),
	bill_city		varchar(100),
	bill_street		varchar(100),
	bill_pincode	varchar(50),
	bill_website	varchar(50),
	bill_phone_no	varchar(50),
	bill_fax_no		varchar(50),
	bill_mobile_no	varchar(50),
	shipping_id 	integer,
	ship_address1	varchar(200),
	ship_address2	varchar(200),
	ship_country	varchar(100),
	ship_state		varchar(100),
	ship_city		varchar(100),
	ship_street		varchar(100),
	ship_pincode	varchar(50),
	ship_website	varchar(50),
	ship_phone_no	varchar(50),
	ship_fax_no		varchar(50),
	ship_mobile_no	varchar(50),
	note 			text,
	terms_conditions text,
	company_id 		integer not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_id),
	CONSTRAINT tbl_item_purchase_return_invoice_main_fk1 FOREIGN KEY(supplier_id) REFERENCES tbl_supplier(supplier_id),
	constraint tbl_item_purchase_return_invoice_main_fk2 FOREIGN key(company_id) references public.tbl_company(company_id),
	constraint tbl_item_purchase_return_invoice_main_fk3 FOREIGN key(payment_type_id) references tbl_payment_type(payment_type_id)
);
create SEQUENCE tbl_item_purchase_return_invoice_det_seq;
create table if not exists tbl_item_purchase_return_invoice_det
(
	inv_det_id integer not null default nextval('tbl_item_purchase_return_invoice_det_seq'),
	inv_id 		integer not null,
	ref_inv_type 	varchar(30),
	ref_inv_id  	integer,
	ref_inv_det_id  integer,
	item_id 	integer not null,
	item_description text,
	bin_id 		integer not null,
	inv_qty	numeric(20,4) default 0 not null,
	uom		varchar(50) not null,
	input_rate	numeric(20,4) default 0 not null,
	input_amt	numeric(20,4) default 0 not null,
	conf_qty	numeric(20,4) default 0 not null,
	ret_qty	numeric(20,4) default 0 not null,
	conf_input_rate	numeric(20,4) default 0 not null,
	conf_input_amt	numeric(20,4) default 0 not null,
	ret_input_rate	numeric(20,4) default 0 not null,
	ret_input_amt	numeric(20,4) default 0 not null,
	discount_type   varchar(50),
	discount_value    numeric(20,4),
	cost_price numeric(20,4) default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_det_id)	,
	CONSTRAINT tbl_item_purchase_return_invoice_det_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_purchase_return_invoice_main(inv_id),
	CONSTRAINT tbl_item_purchase_return_invoice_det_fk2 FOREIGN KEY(item_id) REFERENCES tbl_item(item_id),
	CONSTRAINT tbl_item_purchase_return_invoice_det_fk3 FOREIGN KEY(bin_id) REFERENCES tbl_bin(bin_id)
);

create SEQUENCE tbl_item_purchase_return_invoice_chgs_seq;
create table if not exists tbl_item_purchase_return_invoice_chgs
(
	charge_id  integer not null default nextval('tbl_item_purchase_return_invoice_chgs_seq'),
	inv_id     			integer not null,
	charge_name      	varchar(100) not null,
	plus_minus_flag  	integer not null,
	input_pct_amt_type 	varchar(50) not null,
	input_pct_amt_value numeric(20,4) default 0 not null,
	input_amt 			numeric(20,4) default 0 not null,
	is_supplier_payable integer default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(charge_id),
	CONSTRAINT tbl_item_purchase_return_invoice_chgs_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_purchase_return_invoice_main(inv_id)
);

create SEQUENCE tbl_item_sales_invoice_main_seq;
create table if not exists tbl_item_sales_invoice_main
(
	inv_id 		integer not null default nextval('tbl_item_sales_invoice_main_seq'),
	inv_type 	varchar(30) not null,
	inv_no 		varchar(30) not null,
	REFERENCE_no varchar(50),
	inv_dt 		date not null,
	inv_due_dt	date not null,
	inv_due_months numeric(20,4) default 0 not null,
	inv_due_days 	numeric(20,4) default 0 not null,
	currency 		varchar(50) not null,
	exchange_rate numeric(20,4) default 0 not null,
	customer_id integer not null,
	head_salesman_id 	integer not null,
	salesman_id 		integer not null,
	payment_type_id 	integer not null,
	shipment_type_id 	integer,
	carrier_id 		integer,
	shipment_company_name varchar(50),
	tracking_no varchar(50),
	tracking_status varchar(50),
	inv_status			varchar(50) not null,
	payment_status		varchar(50) not null,
	cancel_hold_status	varchar(50),
	accounting_status	varchar(50) not null,
	document_url		varchar(200),
	order_id integer,
	total_invoice_qty numeric(20,4) default 0 not null,
	total_invoice_amount		numeric(20,4) default 0 not null,
	party_payable_amount   numeric(20,4) default 0 not null,
	charges_plus_amount    numeric(20,4) default 0 not null,
	charges_minus_amount   numeric(20,4) default 0 not null,
	total_invoice_gross_amount numeric(20,4) default 0 not null,
	total_received_amount		numeric(20,4) default 0 not null,
	billing_id 		integer,
	bill_address1	varchar(200),
	bill_address2	varchar(200),
	bill_country	varchar(100),
	bill_state		varchar(100),
	bill_city		varchar(100),
	bill_street		varchar(100),
	bill_pincode	varchar(50),
	bill_website	varchar(50),
	bill_phone_no	varchar(50),
	bill_fax_no		varchar(50),
	bill_mobile_no	varchar(50),
	shipping_id 	integer,
	ship_address1	varchar(200),
	ship_address2	varchar(200),
	ship_country	varchar(100),
	ship_state		varchar(100),
	ship_city		varchar(100),
	ship_street		varchar(100),
	ship_pincode	varchar(50),
	ship_website	varchar(50),
	ship_phone_no	varchar(50),
	ship_fax_no		varchar(50),
	ship_mobile_no	varchar(50),
	company_id 		integer not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_id),
	CONSTRAINT tbl_item_sales_invoice_main_fk1 FOREIGN KEY(customer_id) REFERENCES tbl_customer(customer_id),
	CONSTRAINT tbl_item_sales_invoice_main_fk2 FOREIGN KEY(payment_type_id) REFERENCES tbl_payment_type(payment_type_id)
);
create SEQUENCE tbl_item_sales_invoice_det_seq;
create table if not exists tbl_item_sales_invoice_det
(
	inv_det_id 		integer not null default nextval('tbl_item_sales_invoice_det_seq'),
	inv_id 			integer not null,
	product_id 		integer not null,
	bin_id 			integer not null,
	prod_description text,
	inv_qty	numeric(20,4) default 0 not null,
	uom		varchar(50) not null,
	input_rate	numeric(20,4) default 0 not null,
	input_amt	numeric(20,4) default 0 not null,
	conf_qty	numeric(20,4) default 0 not null,
	ret_qty	numeric(20,4) default 0 not null,
	conf_input_rate	numeric(20,4) default 0 not null,
	conf_input_amt	numeric(20,4) default 0 not null,
	ret_input_rate	numeric(20,4) default 0 not null,
	ret_input_amt	numeric(20,4) default 0 not null,
	discount_type   varchar(50),
	discount_value    numeric(20,4) default 0 not null,
	cost_price 		numeric(20,4) default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_det_id)	,
	CONSTRAINT tbl_item_sales_invoice_det_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_sales_invoice_main(inv_id),
	CONSTRAINT tbl_item_sales_invoice_det_fk2 FOREIGN KEY(product_id) REFERENCES tbl_product(product_id),
	CONSTRAINT tbl_item_sales_invoice_det_fk3 FOREIGN KEY(bin_id) REFERENCES tbl_bin(bin_id)
);


create SEQUENCE tbl_item_sales_invoice_chgs_seq;
create table if not exists tbl_item_sales_invoice_chgs
(
	charge_id  integer not null default nextval('tbl_item_sales_invoice_chgs_seq'),
	inv_id     			integer not null,
	charge_name      	varchar(100) not null,
	plus_minus_flag  	integer not null,
	input_pct_amt_type 	varchar(50) not null,
	input_pct_amt_value numeric(20,4) default 0 not null,
	input_amt 			numeric(20,4) default 0 not null,
	is_customer_payable integer default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(charge_id),
	CONSTRAINT tbl_item_sales_invoice_chgs_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_sales_invoice_main(inv_id)
);

create SEQUENCE tbl_item_sales_return_invoice_main_seq;
create table if not exists tbl_item_sales_return_invoice_main
(
	inv_id 		integer not null default nextval('tbl_item_sales_return_invoice_main_seq'),
	inv_type 	varchar(30) not null,
	inv_no 		varchar(30) not null,
	REFERENCE_no varchar(50),
	inv_dt 		date not null,
	inv_due_dt	date not null,
	inv_due_months numeric(20,4) default 0 not null,
	inv_due_days 	numeric(20,4) default 0 not null,
	currency 		varchar(50) not null,
	exchange_rate numeric(20,4) default 0 not null,
	customer_id integer not null,
	head_salesman_id 	integer not null,
	salesman_id 		integer not null,
	payment_type_id 	integer not null,
	shipment_type_id 	integer,
	carrier_id 		integer,
	shipment_company_name varchar(50),
	tracking_no varchar(50),
	tracking_status varchar(50),
	inv_status			varchar(50) not null,
	payment_status		varchar(50) not null,
	cancel_hold_status	varchar(50),
	accounting_status	varchar(50) not null,
	document_url		varchar(200),
	order_id integer,
	total_invoice_qty1 numeric(20,4) default 0 not null,
	total_invoice_qty2 numeric(20,4) default 0 not null,
	total_invoice_amount		numeric(20,4) default 0 not null,
	party_payable_amount   numeric(20,4) default 0 not null,
	charges_plus_amount    numeric(20,4) default 0 not null,
	charges_minus_amount   numeric(20,4) default 0 not null,
	total_invoice_gross_amount numeric(20,4) default 0 not null,
	total_received_amount		numeric(20,4) default 0 not null,
	billing_id 		integer,
	bill_address1	varchar(200),
	bill_address2	varchar(200),
	bill_country	varchar(100),
	bill_state		varchar(100),
	bill_city		varchar(100),
	bill_street		varchar(100),
	bill_pincode	varchar(50),
	bill_website	varchar(50),
	bill_phone_no	varchar(50),
	bill_fax_no		varchar(50),
	bill_mobile_no	varchar(50),
	shipping_id 	integer,
	ship_address1	varchar(200),
	ship_address2	varchar(200),
	ship_country	varchar(100),
	ship_state		varchar(100),
	ship_city		varchar(100),
	ship_street		varchar(100),
	ship_pincode	varchar(50),
	ship_website	varchar(50),
	ship_phone_no	varchar(50),
	ship_fax_no		varchar(50),
	ship_mobile_no	varchar(50),
	company_id 		integer not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_id),
	CONSTRAINT tbl_item_sales_return_invoice_main_fk1 FOREIGN KEY(customer_id) REFERENCES tbl_customer(customer_id),
	CONSTRAINT tbl_item_sales_return_invoice_main_fk2 FOREIGN KEY(payment_type_id) REFERENCES tbl_payment_type(payment_type_id)
);
create SEQUENCE tbl_item_sales_return_invoice_det_seq;
create table if not exists tbl_item_sales_return_invoice_det
(
	inv_det_id 		integer not null default nextval('tbl_item_sales_return_invoice_det_seq'),
	inv_id 			integer not null,
	product_id 		integer not null,
	bin_id 			integer not null,
	prod_description text,
	inv_qty	numeric(20,4) default 0 not null,
	uom		varchar(50) not null,
	input_rate	numeric(20,4) default 0 not null,
	input_amt	numeric(20,4) default 0 not null,
	conf_qty	numeric(20,4) default 0 not null,
	ret_qty	numeric(20,4) default 0 not null,
	conf_input_rate	numeric(20,4) default 0 not null,
	conf_input_amt	numeric(20,4) default 0 not null,
	ret_input_rate	numeric(20,4) default 0 not null,
	ret_input_amt	numeric(20,4) default 0 not null,
	discount_type   varchar(50),
	discount_value    numeric(20,4) default 0 not null,
	cost_price 		numeric(20,4) default 0 not null,
	remarks			text,
	system_remarks	text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(inv_det_id)	,
	CONSTRAINT tbl_item_sales_return_invoice_det_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_sales_return_invoice_main(inv_id),
	CONSTRAINT tbl_item_sales_return_invoice_det_fk2 FOREIGN KEY(product_id) REFERENCES tbl_product(product_id),
	CONSTRAINT tbl_item_sales_return_invoice_det_fk3 FOREIGN KEY(bin_id) REFERENCES tbl_bin(bin_id)
);

create SEQUENCE tbl_item_sales_return_invoice_chgs_seq;
create table if not exists tbl_item_sales_return_invoice_chgs
(
	charge_id           integer not null default nextval('tbl_item_sales_return_invoice_chgs_seq'),
	inv_id     			integer not null,
	charge_name      	varchar(100) not null,
	plus_minus_flag  	integer not null,
	input_pct_amt_type 	varchar(50) not null,
	input_pct_amt_value numeric(20,4) default 0 not null,
	input_amt 			numeric(20,4) default 0 not null,
	is_customer_payable integer default 0 not null,
	remarks			    text,
	system_remarks	    text,
	sort_seq		integer default 0 not null,
	is_locked		integer default 0 not null,
	created_by 		integer NOT NULL,
	created_dt		TIMESTAMP DEFAULT current_timestamp  NOT NULL,
	modified_by 	integer,
	modified_dt		TIMESTAMP,
	is_deleted		integer default 0 not null,
	PRIMARY KEY(charge_id),
	CONSTRAINT tbl_item_sales_return_invoice_chgs_fk1 FOREIGN KEY(inv_id) REFERENCES tbl_item_sales_return_invoice_main(inv_id)
);