ALTER TABLE tbl_subscription_privilege_map ADD CONSTRAINT tbl_subscription_privilege_map_fk3 FOREIGN KEY (menu_id) REFERENCES tbl_menu(menu_id);

update tbl_privilege set fullaccess = false where fullaccess is null;
update tbl_privilege set view = false where view is null;
update tbl_privilege set add = false where add is null;
update tbl_privilege set edit = false where edit is null;
update tbl_privilege set delete = false where delete is null;
update tbl_privilege set print = false where print is null;
update tbl_privilege set share = false where share is null;
update tbl_privilege set email = false where email is null;
update tbl_privilege set detailview = false where detailview is null;
update tbl_privilege set detailadd = false where detailadd is null;
update tbl_privilege set detaildelete = false where detaildelete is null;
update tbl_privilege set mainlock = false where mainlock is null;
update tbl_privilege set mainunlock = false where mainunlock is null;
update tbl_privilege set detaillock = false where detaillock is null;
update tbl_privilege set detailunlock = false where detailunlock is null;
alter table tbl_privilege alter column fullaccess set not null;
alter table tbl_privilege alter column view set not null;
alter table tbl_privilege alter column add set not null;
alter table tbl_privilege alter column edit set not null;
alter table tbl_privilege alter column delete set not null;
alter table tbl_privilege alter column print set not null;
alter table tbl_privilege alter column share set not null;
alter table tbl_privilege alter column email set not null;
alter table tbl_privilege alter column detailview set not null;
alter table tbl_privilege alter column detailadd set not null;
alter table tbl_privilege alter column detaildelete set not null;
alter table tbl_privilege alter column mainlock set not null;
alter table tbl_privilege alter column mainunlock set not null;
alter table tbl_privilege alter column detaillock set not null;
alter table tbl_privilege alter column detailunlock set not null;
ALTER TABLE tbl_privilege ADD quickpayment boolean default false not null;
ALTER TABLE tbl_privilege ADD changestatus boolean default false not null;
ALTER TABLE tbl_privilege ADD upload boolean default false not null;
ALTER TABLE tbl_privilege ADD addcharges boolean default false not null;
ALTER TABLE tbl_privilege ADD deletecharges boolean default false not null;
ALTER TABLE tbl_privilege ADD postaccount boolean default false not null;
ALTER TABLE tbl_privilege ADD submit boolean default false not null;
update tbl_subscription_privilege_map set fullaccess = false where fullaccess is null;
update tbl_subscription_privilege_map set view = false where view is null;
update tbl_subscription_privilege_map set add = false where add is null;
update tbl_subscription_privilege_map set edit = false where edit is null;
update tbl_subscription_privilege_map set delete = false where delete is null;
update tbl_subscription_privilege_map set print = false where print is null;
update tbl_subscription_privilege_map set share = false where share is null;
update tbl_subscription_privilege_map set email = false where email is null;
update tbl_subscription_privilege_map set detailview = false where detailview is null;
update tbl_subscription_privilege_map set detailadd = false where detailadd is null;
update tbl_subscription_privilege_map set detaildelete = false where detaildelete is null;
update tbl_subscription_privilege_map set mainlock = false where mainlock is null;
update tbl_subscription_privilege_map set mainunlock = false where mainunlock is null;
update tbl_subscription_privilege_map set detaillock = false where detaillock is null;
update tbl_subscription_privilege_map set detailunlock = false where detailunlock is null;
alter table tbl_subscription_privilege_map alter column fullaccess set not null;
alter table tbl_subscription_privilege_map alter column view set not null;
alter table tbl_subscription_privilege_map alter column add set not null;
alter table tbl_subscription_privilege_map alter column edit set not null;
alter table tbl_subscription_privilege_map alter column delete set not null;
alter table tbl_subscription_privilege_map alter column print set not null;
alter table tbl_subscription_privilege_map alter column share set not null;
alter table tbl_subscription_privilege_map alter column email set not null;
alter table tbl_subscription_privilege_map alter column detailview set not null;
alter table tbl_subscription_privilege_map alter column detailadd set not null;
alter table tbl_subscription_privilege_map alter column detaildelete set not null;
alter table tbl_subscription_privilege_map alter column mainlock set not null;
alter table tbl_subscription_privilege_map alter column mainunlock set not null;
alter table tbl_subscription_privilege_map alter column detaillock set not null;
alter table tbl_subscription_privilege_map alter column detailunlock set not null;
ALTER TABLE tbl_subscription_privilege_map ADD quickpayment boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD changestatus boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD upload boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD addcharges boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD deletecharges boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD postaccount boolean default false not null;
ALTER TABLE tbl_subscription_privilege_map ADD submit boolean default false not null;
update tbl_role_privilege set fullaccess = false where fullaccess is null;
update tbl_role_privilege set view = false where view is null;
update tbl_role_privilege set add = false where add is null;
update tbl_role_privilege set edit = false where edit is null;
update tbl_role_privilege set delete = false where delete is null;
update tbl_role_privilege set print = false where print is null;
update tbl_role_privilege set share = false where share is null;
update tbl_role_privilege set email = false where email is null;
update tbl_role_privilege set detailview = false where detailview is null;
update tbl_role_privilege set detailadd = false where detailadd is null;
update tbl_role_privilege set detaildelete = false where detaildelete is null;
update tbl_role_privilege set mainlock = false where mainlock is null;
update tbl_role_privilege set mainunlock = false where mainunlock is null;
update tbl_role_privilege set detaillock = false where detaillock is null;
update tbl_role_privilege set detailunlock = false where detailunlock is null;
alter table tbl_role_privilege alter column fullaccess set not null;
alter table tbl_role_privilege alter column view set not null;
alter table tbl_role_privilege alter column add set not null;
alter table tbl_role_privilege alter column edit set not null;
alter table tbl_role_privilege alter column delete set not null;
alter table tbl_role_privilege alter column print set not null;
alter table tbl_role_privilege alter column share set not null;
alter table tbl_role_privilege alter column email set not null;
alter table tbl_role_privilege alter column detailview set not null;
alter table tbl_role_privilege alter column detailadd set not null;
alter table tbl_role_privilege alter column detaildelete set not null;
alter table tbl_role_privilege alter column mainlock set not null;
alter table tbl_role_privilege alter column mainunlock set not null;
alter table tbl_role_privilege alter column detaillock set not null;
alter table tbl_role_privilege alter column detailunlock set not null;
ALTER TABLE tbl_role_privilege ADD quickpayment boolean default false not null;
ALTER TABLE tbl_role_privilege ADD changestatus boolean default false not null;
ALTER TABLE tbl_role_privilege ADD upload boolean default false not null;
ALTER TABLE tbl_role_privilege ADD addcharges boolean default false not null;
ALTER TABLE tbl_role_privilege ADD deletecharges boolean default false not null;
ALTER TABLE tbl_role_privilege ADD postaccount boolean default false not null;
ALTER TABLE tbl_role_privilege ADD submit boolean default false not null;