package com.tekfilo.inventory.util;

public enum UploadTypes {
    RM_PURCHASE,
    RM_SALES,
    RM_MEMO_PURCHASE,
    RM_MEMO_SALES,
    RM_PURCHASE_RETURN,
    RM_SALES_RETURN,
    RM_MEMO_PURCHASE_RETURN,
    RM_MEMO_SALES_RETURN,
    DIAMOND,
    GEMSTONE,
    METAL,
    DIAMOND_IMAGE,
    GEMSTONE_IMAGE,
    PAYMENT_PAID, PAYMENT_RECEIVED, METAL_IMAGE, ITEM_PURCHASE, ITEM_PURCHASE_RETURN, ITEM_SALES, ITEM_SALES_RETURN, ITEM_IMAGE
}
